**Задание**

Загрузите данные, проверьте правильность, наличие пропущенных значений, типы данных.

Создайте новый признак – марку автомобиля (company). Машины каких производителей встречаются в датасете? Далее исправьте названия и проверьте изменения.

Оставьте только часть предикторов, после чего посчитайте корреляцию между price и другими переменными.

Преобразуйте категориальные переменные с помощью pd.get_dummies().

Постройте модель с одним предиктором цены – horsepower. Какой процент изменчивости объясняет полученная модель?

Далее – две модели (со всеми предикторами и со всеми, кроме марок машин). Обратите внимание на изменения в R^2, коэффициентах и их значимости. Какую модель лучше оставить?

Заполните пропуски в результатах.

Постройте модель с одним предиктором цены – horsepower. Какой процент изменчивости объясняет полученная модель? </li>Постройте модель с одним предиктором цены – horsepower. Какой процент изменчивости объясняет полученная модель? </li> <li>Далее – две модели (со всеми предикторами и со всеми, кроме марок машин). Обратите внимание на изменения в R^2, коэффициентах и их значимости. Какую модель лучше оставить?

In [66]:
import pandas as pd
import pingouin as pg
import statsmodels.api as sm

In [ ]:
df = pd.read_csv("../Statistic/data/cars.csv")

In [68]:
df['company'] = df.CarName.apply(lambda x: x.split(' ')[0])

In [69]:
df = df.drop(columns=['CarName', 'car_ID'])

In [70]:
df['company'] = df.company.replace(to_replace={'maxda':'mazda', 
                                               'Nissan':'nissan',
                                               'porcshce':'porsche',
                                               'toyouta':'toyota',
                                               'vokswagen':'volkswagen',
                                               'vw':'volkswagen'
                                               })

In [71]:
df['company'].nunique()

22

In [ ]:
cols_to_keep = [['price'], ['company', 'fueltype', 'aspiration','carbody', 
'drivewheel', 'wheelbase', 'carlength','carwidth', 
'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 
'boreratio','horsepower']]

cols_to_keep1 = ['company', 'fueltype', 'aspiration','carbody', 
'drivewheel', 'wheelbase', 'carlength','carwidth', 
'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 
'boreratio','horsepower', 'price']

df = df[cols_to_keep1]

In [73]:
pg.pairwise_corr(data=df, columns=cols_to_keep)

,X,Y,method,alternative,n,r,CI95%,p-unc,BF10,power
0,price,wheelbase,pearson,two-sided,205,0.577816,"[0.48, 0.66]",1.182820e-19,4.756e+16,1.0
1,price,carlength,pearson,two-sided,205,0.682920,"[0.6, 0.75]",1.678707e-29,2.287e+26,1.0
2,price,carwidth,pearson,two-sided,205,0.759325,"[0.69, 0.81]",9.627438e-40,2.858e+36,1.0
3,price,curbweight,pearson,two-sided,205,0.835305,"[0.79, 0.87]",1.214445e-54,1.477e+51,1.0
4,price,enginesize,pearson,two-sided,205,0.874145,"[0.84, 0.9]",1.354764e-65,9.89e+61,1.0
5,price,boreratio,pearson,two-sided,205,0.553173,"[0.45, 0.64]",7.907922e-18,7.726e+14,1.0
6,price,horsepower,pearson,two-sided,205,0.808139,"[0.75, 0.85]",1.483437e-48,1.432e+45,1.0

In [ ]:
df_dummy = pd.get_dummies(data=df, drop_first=True)
for col in df_dummy.select_dtypes(include='bool').columns:
    df_dummy[col] = df_dummy[col].map({True: 1, False: 0})

C:\Users\user\AppData\Local\Temp\ipykernel_9140\2992151856.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_dummy.replace({True: 1, False: 0})

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,...,CarName_volkswagen type 3,CarName_volvo 144ea,CarName_volvo 145e (sw),CarName_volvo 244dl,CarName_volvo 245,CarName_volvo 246,CarName_volvo 264gl,CarName_volvo diesel,CarName_vw dasher,CarName_vw rabbit
0,1.0,3.0,88.6,168.8,64.1,48.8,2548.0,130.0,3.47,2.68,...,0,0,0,0,0,0,0,0,0,0
1,2.0,3.0,88.6,168.8,64.1,48.8,2548.0,130.0,3.47,2.68,...,0,0,0,0,0,0,0,0,0,0
2,3.0,1.0,94.5,171.2,65.5,52.4,2823.0,152.0,2.68,3.47,...,0,0,0,0,0,0,0,0,0,0
3,4.0,2.0,99.8,176.6,66.2,54.3,2337.0,109.0,3.19,3.40,...,0,0,0,0,0,0,0,0,0,0
4,5.0,2.0,99.4,176.6,66.4,54.3,2824.0,136.0,3.19,3.40,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201.0,-1.0,109.1,188.8,68.9,55.5,2952.0,141.0,3.78,3.15,...,0,0,1,0,0,0,0,0,0,0
201,202.0,-1.0,109.1,188.8,68.8,55.5,3049.0,141.0,3.78,3.15,...,0,1,0,0,0,0,0,0,0,0
202,203.0,-1.0,109.1,188.8,68.9,55.5,3012.0,173.0,3.58,2.87,...,0,0,0,1,0,0,0,0,0,0
203,204.0,-1.0,109.1,188.8,68.9,55.5,3217.0,145.0,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
204,205.0,-1.0,109.1,188.8,68.9,55.5,3062.0,141.0,3.78,3.15,...,0,0,0,0,0,0,1,0,0,0

In [76]:
import statsmodels.formula.api as smf
formula = "price ~ horsepower"

smf.ols(formula, df).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                 Чт, 26 июн 2025   Prob (F-statistic):           1.48e-48
Time:                        08:59:37   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
df_dummy = pd.get_dummies(data=df, drop_first=True)
for col in df_dummy.select_dtypes(include='bool').columns:
    df_dummy[col] = df_dummy[col].map({True: 1, False: 0})
X = df_dummy.drop(['price'], axis='columns') #предикторы
y = df_dummy['price'] #целевая переменная

#не забываем про константу
X = sm.add_constant(X)

sm.OLS(y, X).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.998
Model:                            OLS   Adj. R-squared:                  0.981
Method:                 Least Squares   F-statistic:                     60.35
Date:                 Чт, 26 июн 2025   Prob (F-statistic):           6.35e-19
Time:                        09:26:19   Log-Likelihood:                -1514.8
No. Observations:                 205   AIC:                             3388.
Df Residuals:                      26   BIC:                             3982.
Df Model:                         178
Covariance Type:            nonrobust
===========================================================================================================
                                              coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
const                                   -7242.2117   1.32e+04     -0.548      0.588   -3.44e+04    1.99e+04
car_ID                                    153.0758     64.684      2.367      0.026      20.116     286.035
symboling                                 725.6677    323.690      2.242      0.034      60.314    1391.021
wheelbase                                 289.8183    128.512      2.255      0.033      25.659     553.978
carlength                                -223.9631     75.521     -2.966      0.006    -379.199     -68.727
carwidth                                  707.8796    306.717      2.308      0.029      77.413    1338.346
carheight                                -461.8343    272.256     -1.696      0.102   -1021.464      97.796
curbweight                                 10.8473      3.395      3.195      0.004       3.868      17.827
enginesize                                 55.5321     50.444      1.101      0.281     -48.157     159.221
boreratio                               -3484.6058   1792.683     -1.944      0.063   -7169.518     200.306
stroke                                  -1314.6572   1072.834     -1.225      0.231   -3519.899     890.585
compressionratio                        -1910.2103    772.424     -2.473      0.020   -3497.950    -322.470
horsepower                                -42.8764     34.010     -1.261      0.219    -112.785      27.033
peakrpm                                     3.2855      1.008      3.261      0.003       1.214       5.357
citympg                                   309.2976    223.210      1.386      0.178    -149.518     768.113
highwaympg                               -124.2183    164.066     -0.757      0.456    -461.461     213.024
fueltype_gas                            -1.733e+04   5952.181     -2.912      0.007   -2.96e+04   -5097.376
aspiration_turbo                          236.2109    986.002      0.240      0.813   -1790.545    2262.967
doornumber_two                          -1289.2036    726.157     -1.775      0.088   -2781.840     203.433
carbody_hardtop                         -1784.6595   2095.609     -0.852      0.402   -6092.246    2522.927
carbody_hatchback                       -1690.0581   1714.327     -0.986      0.333   -5213.907    1833.790
carbody_sedan                            -705.9336   1776.071     -0.397      0.694   -4356.701    2944.834
carbody_wagon                           -2764.7655   1902.533     -1.453      0.158   -6675.478    1145.947
drivewheel_fwd                            220.4660   1260.739      0.175      0.863   -2371.020    2811.952
drivewheel_rwd                            697.1798   1435.842      0.486      0.631   -2254.235    3648.594
enginelocation_rear                      2.243e+04   2443.922      9.176      0.000    1.74e+04    2.74e+04
enginetype_dohcv                        -6978.2395   5581.213     -1.250      0.222   -1.85e+04    4494.109
enginetype_l                            -8187.6329   2648.022     -3.092      0.005   -1.36e+04   -2744.547
enginetype_ohc                          -3823.2898   1866.254     -2.049      0.051   -7659.431      12.851
enginetype_ohcf                         -8211.6228   3122.750     -2.630      0.014   -1.46e+04   -1792.718
enginetype_ohcv                           804.4469   2282.580      0.352      0.727   -3887.464    5496.358
enginetype_rotor                         -843.7711   1663.645     -0.507      0.616   -4263.442    2575.900
cylindernumber_five                      3134.2716   3086.203      1.016      0.319   -3209.508    9478.052
cylindernumber_four                     -4882.7597   3541.655     -1.379      0.180   -1.22e+04    2397.217
cylindernumber_six                      -1.203e+04   2772.493     -4.340      0.000   -1.77e+04   -6333.842
cylindernumber_three                     5157.1592   1973.330      2.613      0.015    1100.921    9213.397
cylindernumber_twelve                    2885.0374   2496.585      1.156      0.258   -2246.766    8016.841
cylindernumber_two                       -843.7711   1663.645     -0.507      0.616   -4263.442    2575.900
fuelsystem_2bbl                          3954.3069   2726.010      1.451      0.159   -1649.088    9557.702
fuelsystem_4bbl                         -3721.6618   2368.611     -1.571      0.128   -8590.411    1147.088
fuelsystem_idi                           1.009e+04   1.01e+04      1.002      0.326   -1.06e+04    3.08e+04
fuelsystem_mfi                           4014.3648   2929.889      1.370      0.182   -2008.107       1e+04
fuelsystem_mpfi                          2993.5553   2482.520      1.206      0.239   -2109.337    8096.448
fuelsystem_spdi                          2526.7106   3442.636      0.734      0.470   -4549.730    9603.151
fuelsystem_spfi                          2068.3750   4073.432      0.508      0.616   -6304.683    1.04e+04
CarName_alfa-romero Quadrifoglio         1.875e+04   6772.509      2.769      0.010    4831.972    3.27e+04
CarName_alfa-romero giulia               1.065e+04   6667.999      1.597      0.122   -3057.260    2.44e+04
CarName_alfa-romero stelvio               1.35e+04   6606.480      2.044      0.051     -78.883    2.71e+04
CarName_audi 100 ls                      1.739e+04   6377.698      2.727      0.011    4284.271    3.05e+04
CarName_audi 100ls                       3687.6839   3356.091      1.099      0.282   -3210.861    1.06e+04
CarName_audi 4000                        7700.1330   3260.703      2.361      0.026     997.661    1.44e+04
CarName_audi 5000                        5562.3945   3195.500      1.741      0.094   -1006.050    1.21e+04
CarName_audi 5000s (diesel)              3295.4528   3278.835      1.005      0.324   -3444.290       1e+04
CarName_audi fox                         6251.3032   3144.388      1.988      0.057    -212.080    1.27e+04
CarName_bmw 320i                         1.708e+04   6228.186      2.742      0.011    4276.778    2.99e+04
CarName_bmw x1                           2.981e+04   6818.294      4.372      0.000    1.58e+04    4.38e+04
CarName_bmw x3                           2.908e+04   6823.301      4.262      0.000    1.51e+04    4.31e+04
CarName_bmw x4                           3.001e+04   6818.820      4.401      0.000     1.6e+04     4.4e+04
CarName_bmw x5                           3.952e+04   6652.521      5.940      0.000    2.58e+04    5.32e+04
CarName_bmw z4                           2.851e+04   6996.210      4.075      0.000    1.41e+04    4.29e+04
CarName_buick century                    1641.2285   2198.753      0.746      0.462   -2878.373    6160.830
CarName_buick century luxus (sw)         1076.8490   2284.558      0.471      0.641   -3619.127    5772.825
CarName_buick century special            1696.8779   4035.328      0.421      0.678   -6597.857    9991.612
CarName_buick electra 225 custom        -1991.8194   1596.608     -1.248      0.223   -5273.695    1290.056
CarName_buick opel isuzu deluxe         -1365.8068   2864.816     -0.477      0.638   -7254.521    4522.907
CarName_buick regal sport coupe (turbo)  9628.3116   3357.567      2.868      0.008    2726.734    1.65e+04
CarName_buick skyhawk                     744.8705   1754.220      0.425      0.675   -2860.981    4350.722
CarName_buick skylark                   -3640.5092   3046.690     -1.195      0.243   -9903.070    2622.051
CarName_chevrolet impala                 5157.1592   1973.330      2.613      0.015    1100.921    9213.397
CarName_chevrolet monte carlo            7621.8502   4840.806      1.575      0.127   -2328.570    1.76e+04
CarName_chevrolet vega 2300              6470.9501   4939.389      1.310      0.202   -3682.109    1.66e+04
CarName_dodge challenger se              7768.8807   4717.120      1.647      0.112   -1927.299    1.75e+04
CarName_dodge colt (sw)                  4797.1339   4606.520      1.041      0.307   -4671.703    1.43e+04
CarName_dodge colt hardtop               4033.2097   4663.079      0.865      0.395   -5551.886    1.36e+04
CarName_dodge coronet custom             4581.5627   4992.861      0.918      0.367   -5681.409    1.48e+04
CarName_dodge coronet custom (sw)        4014.3648   2929.889      1.370      0.182   -2008.107       1e+04
CarName_dodge d200                       6352.7393   5249.045      1.210      0.237   -4436.826    1.71e+04
CarName_dodge dart custom                9932.4707   4874.852      2.037      0.052     -87.932       2e+04
CarName_dodge monaco (sw)                4946.0514   4825.889      1.025      0.315   -4973.706    1.49e+04
CarName_dodge rampage                    5652.9281   4854.753      1.164      0.255   -4326.159    1.56e+04
CarName_honda accord                     1.014e+04   5259.036      1.928      0.065    -671.959    2.09e+04
CarName_honda accord cvcc                6599.0500   4787.955      1.378      0.180   -3242.733    1.64e+04
CarName_honda accord lx                  7819.0237   5135.200      1.523      0.140   -2736.531    1.84e+04
CarName_honda civic                      8792.5136   4199.891      2.094      0.046     159.515    1.74e+04
CarName_honda civic (auto)               5296.1650   3750.856      1.412      0.170   -2413.829     1.3e+04
CarName_honda civic 1300                 9489.0318   5154.127      1.841      0.077   -1105.428    2.01e+04
CarName_honda civic 1500 gl              1.002e+04   4786.517      2.094      0.046     183.729    1.99e+04
CarName_honda civic cvcc                 7482.9244   4648.854      1.610      0.120   -2072.931     1.7e+04
CarName_honda prelude                    8788.6934   5355.314      1.641      0.113   -2219.312    1.98e+04
CarName_isuzu D-Max                      5432.3311   3360.351      1.617      0.118   -1474.970    1.23e+04
CarName_isuzu D-Max V-Cross              4336.0628   3583.490      1.210      0.237   -3029.906    1.17e+04
CarName_isuzu MU-X                       5502.3734   4222.490      1.303      0.204   -3177.079    1.42e+04
CarName_jaguar xf                        1.357e+04   6530.934      2.078      0.048     149.315     2.7e+04
CarName_jaguar xj                        1.043e+04   6586.598      1.583      0.125   -3112.030     2.4e+04
CarName_jaguar xk                        2885.0374   2496.585      1.156      0.258   -2246.766    8016.841
CarName_maxda glc deluxe                 5532.3227   3003.805      1.842      0.077    -642.087    1.17e+04
CarName_maxda rx3                        4333.6415   3162.539      1.370      0.182   -2167.050    1.08e+04
CarName_mazda 626                        4802.7456   3036.226      1.582      0.126   -1438.306     1.1e+04
CarName_mazda glc                        6891.2320   3426.146      2.011      0.055    -151.312    1.39e+04
CarName_mazda glc 4                      2877.8907   2020.747      1.424      0.166   -1275.814    7031.595
CarName_mazda glc custom                 5192.6001   3024.199      1.717      0.098   -1023.730    1.14e+04
CarName_mazda glc custom l               2258.1338   3151.410      0.717      0.480   -4219.682    8735.950
CarName_mazda glc deluxe                 5223.7819   2827.704      1.847      0.076    -588.646     1.1e+04
CarName_mazda rx-4                       4245.6054   2944.980      1.442      0.161   -1807.887    1.03e+04
CarName_mazda rx-7 gs                    7719.2781   3353.485      2.302      0.030     826.092    1.46e+04
CarName_mazda rx2 coupe                  6025.0103   2951.953      2.041      0.052     -42.816    1.21e+04
CarName_mercury cougar                   5235.1228   3120.304      1.678      0.105   -1178.754    1.16e+04
CarName_mitsubishi g4                   -2304.0780   2216.000     -1.040      0.308   -6859.131    2250.975
CarName_mitsubishi lancer               -2837.3653   2178.832     -1.302      0.204   -7316.019    1641.289
CarName_mitsubishi mirage               -4685.3894   2473.827     -1.894      0.069   -9770.414     399.635
CarName_mitsubishi mirage g4            -2657.1777   2380.042     -1.116      0.274   -7549.423    2235.068
CarName_mitsubishi montero              -5234.3203   2133.589     -2.453      0.021   -9619.976    -848.664
CarName_mitsubishi outlander            -3627.5338   2089.236     -1.736      0.094   -7922.019     666.952
CarName_mitsubishi pajero               -4621.2894   2141.237     -2.158      0.040   -9022.666    -219.913
CarName_nissan clipper                  -1047.8335   2302.315     -0.455      0.653   -5780.309    3684.642
CarName_nissan dayz                     -2124.1450   2653.672     -0.800      0.431   -7578.846    3330.556
CarName_nissan fuga                      -387.3755   3147.508     -0.123      0.903   -6857.170    6082.419
CarName_nissan gt-r                     -2187.3848   2069.049     -1.057      0.300   -6440.377    2065.607
CarName_nissan juke                       370.8784   1757.810      0.211      0.835   -3242.353    3984.109
CarName_nissan kicks                    -1051.4806   3177.680     -0.331      0.743   -7583.295    5480.333
CarName_nissan latio                    -1090.0828   1543.817     -0.706      0.486   -4263.445    2083.279
CarName_nissan leaf                       362.0865   1606.924      0.225      0.823   -2940.993    3665.166
CarName_nissan note                      1075.2014   2005.249      0.536      0.596   -3046.648    5197.051
CarName_nissan nv200                    -2611.8753   1733.816     -1.506      0.144   -6175.786     952.035
CarName_nissan otti                     -1647.0873   2641.109     -0.624      0.538   -7075.964    3781.790
CarName_nissan rogue                     -892.0203   1443.056     -0.618      0.542   -3858.264    2074.224
CarName_nissan teana                    -2217.5383   2920.089     -0.759      0.454   -8219.867    3784.790
CarName_nissan titan                     1178.5199   1935.666      0.609      0.548   -2800.298    5157.338
CarName_peugeot 304                     -4788.1475   1385.381     -3.456      0.002   -7635.840   -1940.455
CarName_peugeot 504                     -2377.3429   1017.272     -2.337      0.027   -4468.377    -286.309
CarName_peugeot 504 (sw)                -2108.2233   1544.080     -1.365      0.184   -5282.124    1065.678
CarName_peugeot 505s turbo diesel       -1132.4928   1395.961     -0.811      0.425   -4001.932    1736.947
CarName_peugeot 604sl                   -2938.5855   1214.317     -2.420      0.023   -5434.649    -442.522
CarName_plymouth cricket                -7875.6907   3003.093     -2.623      0.014    -1.4e+04   -1702.745
CarName_plymouth duster                 -9880.2573   2950.834     -3.348      0.002   -1.59e+04   -3814.731
CarName_plymouth fury gran sedan         -1.02e+04   2963.093     -3.443      0.002   -1.63e+04   -4110.836
CarName_plymouth fury iii               -9709.6678   2934.833     -3.308      0.003   -1.57e+04   -3677.033
CarName_plymouth satellite custom (sw)  -8330.0675   2791.684     -2.984      0.006   -1.41e+04   -2591.678
CarName_plymouth valiant                -4574.8820   2882.580     -1.587      0.125   -1.05e+04    1350.346
CarName_porcshce panamera                4056.0235   1863.448      2.177      0.039     225.650    7886.397
CarName_porsche boxter                   5987.9298   2871.715      2.085      0.047      85.035    1.19e+04
CarName_porsche cayenne                  5402.9477   1766.824      3.058      0.005    1771.190    9034.706
CarName_porsche macan                    1381.8169   3276.816      0.422      0.677   -5353.775    8117.408
CarName_renault 12tl                    -4372.7902   2965.159     -1.475      0.152   -1.05e+04    1722.182
CarName_renault 5 gtl                   -7165.9082   2932.311     -2.444      0.022   -1.32e+04   -1138.457
CarName_saab 99e                        -2956.7825   3388.110     -0.873      0.391   -9921.142    4007.577
CarName_saab 99gle                      -1855.2530   3468.986     -0.535      0.597   -8985.856    5275.350
CarName_saab 99le                       -4814.2690   3329.496     -1.446      0.160   -1.17e+04    2029.608
CarName_subaru                          -5451.0941   1235.590     -4.412      0.000   -7990.885   -2911.303
CarName_subaru baja                     -3844.3156   1359.284     -2.828      0.009   -6638.363   -1050.268
CarName_subaru brz                      -2635.2611   1408.007     -1.872      0.073   -5529.461     258.939
CarName_subaru dl                       -3223.5947   1182.722     -2.726      0.011   -5654.714    -792.476
CarName_subaru r1                       -4514.7818   1751.479     -2.578      0.016   -8114.998    -914.566
CarName_subaru r2                       -4016.2176   1777.630     -2.259      0.032   -7670.189    -362.247
CarName_subaru trezia                   -4354.1732   1670.111     -2.607      0.015   -7787.135    -921.211
CarName_subaru tribeca                  -2597.3253   1617.388     -1.606      0.120   -5921.915     727.264
CarName_toyota carina                     -1.5e+04   5878.672     -2.551      0.017   -2.71e+04   -2911.903
CarName_toyota celica gt                -1.239e+04   5321.290     -2.329      0.028   -2.33e+04   -1453.844
CarName_toyota celica gt liftback       -1.773e+04   5025.300     -3.528      0.002   -2.81e+04   -7401.845
CarName_toyota corolla                  -1.152e+04   4575.198     -2.518      0.018   -2.09e+04   -2116.025
CarName_toyota corolla 1200             -1.171e+04   4363.923     -2.683      0.013   -2.07e+04   -2737.169
CarName_toyota corolla 1600 (sw)        -6827.7964   4575.744     -1.492      0.148   -1.62e+04    2577.780
CarName_toyota corolla liftback         -1.166e+04   4730.119     -2.465      0.021   -2.14e+04   -1935.286
CarName_toyota corolla tercel           -1.704e+04   5072.195     -3.360      0.002   -2.75e+04   -6614.058
CarName_toyota corona                   -1.189e+04   4562.672     -2.605      0.015   -2.13e+04   -2507.387
CarName_toyota corona hardtop           -8382.8122   4862.340     -1.724      0.097   -1.84e+04    1611.870
CarName_toyota corona liftback          -1.271e+04   4675.314     -2.718      0.012   -2.23e+04   -3095.339
CarName_toyota corona mark ii           -1.238e+04   4412.183     -2.806      0.009   -2.15e+04   -3312.207
CarName_toyota cressida                 -1.029e+04   5436.045     -1.893      0.069   -2.15e+04     881.571
CarName_toyota mark ii                  -1.137e+04   4620.714     -2.461      0.021   -2.09e+04   -1873.577
CarName_toyota starlet                  -1.168e+04   4472.314     -2.611      0.015   -2.09e+04   -2484.906
CarName_toyota tercel                   -1.192e+04   4971.404     -2.398      0.024   -2.21e+04   -1703.723
CarName_toyouta tercel                  -9056.6737   5022.304     -1.803      0.083   -1.94e+04    1266.820
CarName_vokswagen rabbit                -1.473e+04   6434.181     -2.290      0.030    -2.8e+04   -1507.478

In [99]:
cols_to_keep = df_dummy.columns[~df_dummy.columns.str.startswith('company_')]
df_dummy_no_company = df_dummy[cols_to_keep]

X = df_dummy_no_company.drop(['price'], axis='columns') #предикторы
y = df_dummy_no_company['price'] #целевая переменная

#не забываем про константу
X = sm.add_constant(X)

sm.OLS(y, X).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.998
Model:                            OLS   Adj. R-squared:                  0.981
Method:                 Least Squares   F-statistic:                     60.35
Date:                 Чт, 26 июн 2025   Prob (F-statistic):           6.35e-19
Time:                        09:29:27   Log-Likelihood:                -1514.8
No. Observations:                 205   AIC:                             3388.
Df Residuals:                      26   BIC:                             3982.
Df Model:                         178
Covariance Type:            nonrobust
===========================================================================================================
                                              coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
const                                   -7242.2117   1.32e+04     -0.548      0.588   -3.44e+04    1.99e+04
car_ID                                    153.0758     64.684      2.367      0.026      20.116     286.035
symboling                                 725.6677    323.690      2.242      0.034      60.314    1391.021
wheelbase                                 289.8183    128.512      2.255      0.033      25.659     553.978
carlength                                -223.9631     75.521     -2.966      0.006    -379.199     -68.727
carwidth                                  707.8796    306.717      2.308      0.029      77.413    1338.346
carheight                                -461.8343    272.256     -1.696      0.102   -1021.464      97.796
curbweight                                 10.8473      3.395      3.195      0.004       3.868      17.827
enginesize                                 55.5321     50.444      1.101      0.281     -48.157     159.221
boreratio                               -3484.6058   1792.683     -1.944      0.063   -7169.518     200.306
stroke                                  -1314.6572   1072.834     -1.225      0.231   -3519.899     890.585
compressionratio                        -1910.2103    772.424     -2.473      0.020   -3497.950    -322.470
horsepower                                -42.8764     34.010     -1.261      0.219    -112.785      27.033
peakrpm                                     3.2855      1.008      3.261      0.003       1.214       5.357
citympg                                   309.2976    223.210      1.386      0.178    -149.518     768.113
highwaympg                               -124.2183    164.066     -0.757      0.456    -461.461     213.024
fueltype_gas                            -1.733e+04   5952.181     -2.912      0.007   -2.96e+04   -5097.376
aspiration_turbo                          236.2109    986.002      0.240      0.813   -1790.545    2262.967
doornumber_two                          -1289.2036    726.157     -1.775      0.088   -2781.840     203.433
carbody_hardtop                         -1784.6595   2095.609     -0.852      0.402   -6092.246    2522.927
carbody_hatchback                       -1690.0581   1714.327     -0.986      0.333   -5213.907    1833.790
carbody_sedan                            -705.9336   1776.071     -0.397      0.694   -4356.701    2944.834
carbody_wagon                           -2764.7655   1902.533     -1.453      0.158   -6675.478    1145.947
drivewheel_fwd                            220.4660   1260.739      0.175      0.863   -2371.020    2811.952
drivewheel_rwd                            697.1798   1435.842      0.486      0.631   -2254.235    3648.594
enginelocation_rear                      2.243e+04   2443.922      9.176      0.000    1.74e+04    2.74e+04
enginetype_dohcv                        -6978.2395   5581.213     -1.250      0.222   -1.85e+04    4494.109
enginetype_l                            -8187.6329   2648.022     -3.092      0.005   -1.36e+04   -2744.547
enginetype_ohc                          -3823.2898   1866.254     -2.049      0.051   -7659.431      12.851
enginetype_ohcf                         -8211.6228   3122.750     -2.630      0.014   -1.46e+04   -1792.718
enginetype_ohcv                           804.4469   2282.580      0.352      0.727   -3887.464    5496.358
enginetype_rotor                         -843.7711   1663.645     -0.507      0.616   -4263.442    2575.900
cylindernumber_five                      3134.2716   3086.203      1.016      0.319   -3209.508    9478.052
cylindernumber_four                     -4882.7597   3541.655     -1.379      0.180   -1.22e+04    2397.217
cylindernumber_six                      -1.203e+04   2772.493     -4.340      0.000   -1.77e+04   -6333.842
cylindernumber_three                     5157.1592   1973.330      2.613      0.015    1100.921    9213.397
cylindernumber_twelve                    2885.0374   2496.585      1.156      0.258   -2246.766    8016.841
cylindernumber_two                       -843.7711   1663.645     -0.507      0.616   -4263.442    2575.900
fuelsystem_2bbl                          3954.3069   2726.010      1.451      0.159   -1649.088    9557.702
fuelsystem_4bbl                         -3721.6618   2368.611     -1.571      0.128   -8590.411    1147.088
fuelsystem_idi                           1.009e+04   1.01e+04      1.002      0.326   -1.06e+04    3.08e+04
fuelsystem_mfi                           4014.3648   2929.889      1.370      0.182   -2008.107       1e+04
fuelsystem_mpfi                          2993.5553   2482.520      1.206      0.239   -2109.337    8096.448
fuelsystem_spdi                          2526.7106   3442.636      0.734      0.470   -4549.730    9603.151
fuelsystem_spfi                          2068.3750   4073.432      0.508      0.616   -6304.683    1.04e+04
CarName_alfa-romero Quadrifoglio         1.875e+04   6772.509      2.769      0.010    4831.972    3.27e+04
CarName_alfa-romero giulia               1.065e+04   6667.999      1.597      0.122   -3057.260    2.44e+04
CarName_alfa-romero stelvio               1.35e+04   6606.480      2.044      0.051     -78.883    2.71e+04
CarName_audi 100 ls                      1.739e+04   6377.698      2.727      0.011    4284.271    3.05e+04
CarName_audi 100ls                       3687.6839   3356.091      1.099      0.282   -3210.861    1.06e+04
CarName_audi 4000                        7700.1330   3260.703      2.361      0.026     997.661    1.44e+04
CarName_audi 5000                        5562.3945   3195.500      1.741      0.094   -1006.050    1.21e+04
CarName_audi 5000s (diesel)              3295.4528   3278.835      1.005      0.324   -3444.290       1e+04
CarName_audi fox                         6251.3032   3144.388      1.988      0.057    -212.080    1.27e+04
CarName_bmw 320i                         1.708e+04   6228.186      2.742      0.011    4276.778    2.99e+04
CarName_bmw x1                           2.981e+04   6818.294      4.372      0.000    1.58e+04    4.38e+04
CarName_bmw x3                           2.908e+04   6823.301      4.262      0.000    1.51e+04    4.31e+04
CarName_bmw x4                           3.001e+04   6818.820      4.401      0.000     1.6e+04     4.4e+04
CarName_bmw x5                           3.952e+04   6652.521      5.940      0.000    2.58e+04    5.32e+04
CarName_bmw z4                           2.851e+04   6996.210      4.075      0.000    1.41e+04    4.29e+04
CarName_buick century                    1641.2285   2198.753      0.746      0.462   -2878.373    6160.830
CarName_buick century luxus (sw)         1076.8490   2284.558      0.471      0.641   -3619.127    5772.825
CarName_buick century special            1696.8779   4035.328      0.421      0.678   -6597.857    9991.612
CarName_buick electra 225 custom        -1991.8194   1596.608     -1.248      0.223   -5273.695    1290.056
CarName_buick opel isuzu deluxe         -1365.8068   2864.816     -0.477      0.638   -7254.521    4522.907
CarName_buick regal sport coupe (turbo)  9628.3116   3357.567      2.868      0.008    2726.734    1.65e+04
CarName_buick skyhawk                     744.8705   1754.220      0.425      0.675   -2860.981    4350.722
CarName_buick skylark                   -3640.5092   3046.690     -1.195      0.243   -9903.070    2622.051
CarName_chevrolet impala                 5157.1592   1973.330      2.613      0.015    1100.921    9213.397
CarName_chevrolet monte carlo            7621.8502   4840.806      1.575      0.127   -2328.570    1.76e+04
CarName_chevrolet vega 2300              6470.9501   4939.389      1.310      0.202   -3682.109    1.66e+04
CarName_dodge challenger se              7768.8807   4717.120      1.647      0.112   -1927.299    1.75e+04
CarName_dodge colt (sw)                  4797.1339   4606.520      1.041      0.307   -4671.703    1.43e+04
CarName_dodge colt hardtop               4033.2097   4663.079      0.865      0.395   -5551.886    1.36e+04
CarName_dodge coronet custom             4581.5627   4992.861      0.918      0.367   -5681.409    1.48e+04
CarName_dodge coronet custom (sw)        4014.3648   2929.889      1.370      0.182   -2008.107       1e+04
CarName_dodge d200                       6352.7393   5249.045      1.210      0.237   -4436.826    1.71e+04
CarName_dodge dart custom                9932.4707   4874.852      2.037      0.052     -87.932       2e+04
CarName_dodge monaco (sw)                4946.0514   4825.889      1.025      0.315   -4973.706    1.49e+04
CarName_dodge rampage                    5652.9281   4854.753      1.164      0.255   -4326.159    1.56e+04
CarName_honda accord                     1.014e+04   5259.036      1.928      0.065    -671.959    2.09e+04
CarName_honda accord cvcc                6599.0500   4787.955      1.378      0.180   -3242.733    1.64e+04
CarName_honda accord lx                  7819.0237   5135.200      1.523      0.140   -2736.531    1.84e+04
CarName_honda civic                      8792.5136   4199.891      2.094      0.046     159.515    1.74e+04
CarName_honda civic (auto)               5296.1650   3750.856      1.412      0.170   -2413.829     1.3e+04
CarName_honda civic 1300                 9489.0318   5154.127      1.841      0.077   -1105.428    2.01e+04
CarName_honda civic 1500 gl              1.002e+04   4786.517      2.094      0.046     183.729    1.99e+04
CarName_honda civic cvcc                 7482.9244   4648.854      1.610      0.120   -2072.931     1.7e+04
CarName_honda prelude                    8788.6934   5355.314      1.641      0.113   -2219.312    1.98e+04
CarName_isuzu D-Max                      5432.3311   3360.351      1.617      0.118   -1474.970    1.23e+04
CarName_isuzu D-Max V-Cross              4336.0628   3583.490      1.210      0.237   -3029.906    1.17e+04
CarName_isuzu MU-X                       5502.3734   4222.490      1.303      0.204   -3177.079    1.42e+04
CarName_jaguar xf                        1.357e+04   6530.934      2.078      0.048     149.315     2.7e+04
CarName_jaguar xj                        1.043e+04   6586.598      1.583      0.125   -3112.030     2.4e+04
CarName_jaguar xk                        2885.0374   2496.585      1.156      0.258   -2246.766    8016.841
CarName_maxda glc deluxe                 5532.3227   3003.805      1.842      0.077    -642.087    1.17e+04
CarName_maxda rx3                        4333.6415   3162.539      1.370      0.182   -2167.050    1.08e+04
CarName_mazda 626                        4802.7456   3036.226      1.582      0.126   -1438.306     1.1e+04
CarName_mazda glc                        6891.2320   3426.146      2.011      0.055    -151.312    1.39e+04
CarName_mazda glc 4                      2877.8907   2020.747      1.424      0.166   -1275.814    7031.595
CarName_mazda glc custom                 5192.6001   3024.199      1.717      0.098   -1023.730    1.14e+04
CarName_mazda glc custom l               2258.1338   3151.410      0.717      0.480   -4219.682    8735.950
CarName_mazda glc deluxe                 5223.7819   2827.704      1.847      0.076    -588.646     1.1e+04
CarName_mazda rx-4                       4245.6054   2944.980      1.442      0.161   -1807.887    1.03e+04
CarName_mazda rx-7 gs                    7719.2781   3353.485      2.302      0.030     826.092    1.46e+04
CarName_mazda rx2 coupe                  6025.0103   2951.953      2.041      0.052     -42.816    1.21e+04
CarName_mercury cougar                   5235.1228   3120.304      1.678      0.105   -1178.754    1.16e+04
CarName_mitsubishi g4                   -2304.0780   2216.000     -1.040      0.308   -6859.131    2250.975
CarName_mitsubishi lancer               -2837.3653   2178.832     -1.302      0.204   -7316.019    1641.289
CarName_mitsubishi mirage               -4685.3894   2473.827     -1.894      0.069   -9770.414     399.635
CarName_mitsubishi mirage g4            -2657.1777   2380.042     -1.116      0.274   -7549.423    2235.068
CarName_mitsubishi montero              -5234.3203   2133.589     -2.453      0.021   -9619.976    -848.664
CarName_mitsubishi outlander            -3627.5338   2089.236     -1.736      0.094   -7922.019     666.952
CarName_mitsubishi pajero               -4621.2894   2141.237     -2.158      0.040   -9022.666    -219.913
CarName_nissan clipper                  -1047.8335   2302.315     -0.455      0.653   -5780.309    3684.642
CarName_nissan dayz                     -2124.1450   2653.672     -0.800      0.431   -7578.846    3330.556
CarName_nissan fuga                      -387.3755   3147.508     -0.123      0.903   -6857.170    6082.419
CarName_nissan gt-r                     -2187.3848   2069.049     -1.057      0.300   -6440.377    2065.607
CarName_nissan juke                       370.8784   1757.810      0.211      0.835   -3242.353    3984.109
CarName_nissan kicks                    -1051.4806   3177.680     -0.331      0.743   -7583.295    5480.333
CarName_nissan latio                    -1090.0828   1543.817     -0.706      0.486   -4263.445    2083.279
CarName_nissan leaf                       362.0865   1606.924      0.225      0.823   -2940.993    3665.166
CarName_nissan note                      1075.2014   2005.249      0.536      0.596   -3046.648    5197.051
CarName_nissan nv200                    -2611.8753   1733.816     -1.506      0.144   -6175.786     952.035
CarName_nissan otti                     -1647.0873   2641.109     -0.624      0.538   -7075.964    3781.790
CarName_nissan rogue                     -892.0203   1443.056     -0.618      0.542   -3858.264    2074.224
CarName_nissan teana                    -2217.5383   2920.089     -0.759      0.454   -8219.867    3784.790
CarName_nissan titan                     1178.5199   1935.666      0.609      0.548   -2800.298    5157.338
CarName_peugeot 304                     -4788.1475   1385.381     -3.456      0.002   -7635.840   -1940.455
CarName_peugeot 504                     -2377.3429   1017.272     -2.337      0.027   -4468.377    -286.309
CarName_peugeot 504 (sw)                -2108.2233   1544.080     -1.365      0.184   -5282.124    1065.678
CarName_peugeot 505s turbo diesel       -1132.4928   1395.961     -0.811      0.425   -4001.932    1736.947
CarName_peugeot 604sl                   -2938.5855   1214.317     -2.420      0.023   -5434.649    -442.522
CarName_plymouth cricket                -7875.6907   3003.093     -2.623      0.014    -1.4e+04   -1702.745
CarName_plymouth duster                 -9880.2573   2950.834     -3.348      0.002   -1.59e+04   -3814.731
CarName_plymouth fury gran sedan         -1.02e+04   2963.093     -3.443      0.002   -1.63e+04   -4110.836
CarName_plymouth fury iii               -9709.6678   2934.833     -3.308      0.003   -1.57e+04   -3677.033
CarName_plymouth satellite custom (sw)  -8330.0675   2791.684     -2.984      0.006   -1.41e+04   -2591.678
CarName_plymouth valiant                -4574.8820   2882.580     -1.587      0.125   -1.05e+04    1350.346
CarName_porcshce panamera                4056.0235   1863.448      2.177      0.039     225.650    7886.397
CarName_porsche boxter                   5987.9298   2871.715      2.085      0.047      85.035    1.19e+04
CarName_porsche cayenne                  5402.9477   1766.824      3.058      0.005    1771.190    9034.706
CarName_porsche macan                    1381.8169   3276.816      0.422      0.677   -5353.775    8117.408
CarName_renault 12tl                    -4372.7902   2965.159     -1.475      0.152   -1.05e+04    1722.182
CarName_renault 5 gtl                   -7165.9082   2932.311     -2.444      0.022   -1.32e+04   -1138.457
CarName_saab 99e                        -2956.7825   3388.110     -0.873      0.391   -9921.142    4007.577
CarName_saab 99gle                      -1855.2530   3468.986     -0.535      0.597   -8985.856    5275.350
CarName_saab 99le                       -4814.2690   3329.496     -1.446      0.160   -1.17e+04    2029.608
CarName_subaru                          -5451.0941   1235.590     -4.412      0.000   -7990.885   -2911.303
CarName_subaru baja                     -3844.3156   1359.284     -2.828      0.009   -6638.363   -1050.268
CarName_subaru brz                      -2635.2611   1408.007     -1.872      0.073   -5529.461     258.939
CarName_subaru dl                       -3223.5947   1182.722     -2.726      0.011   -5654.714    -792.476
CarName_subaru r1                       -4514.7818   1751.479     -2.578      0.016   -8114.998    -914.566
CarName_subaru r2                       -4016.2176   1777.630     -2.259      0.032   -7670.189    -362.247
CarName_subaru trezia                   -4354.1732   1670.111     -2.607      0.015   -7787.135    -921.211
CarName_subaru tribeca                  -2597.3253   1617.388     -1.606      0.120   -5921.915     727.264
CarName_toyota carina                     -1.5e+04   5878.672     -2.551      0.017   -2.71e+04   -2911.903
CarName_toyota celica gt                -1.239e+04   5321.290     -2.329      0.028   -2.33e+04   -1453.844
CarName_toyota celica gt liftback       -1.773e+04   5025.300     -3.528      0.002   -2.81e+04   -7401.845
CarName_toyota corolla                  -1.152e+04   4575.198     -2.518      0.018   -2.09e+04   -2116.025
CarName_toyota corolla 1200             -1.171e+04   4363.923     -2.683      0.013   -2.07e+04   -2737.169
CarName_toyota corolla 1600 (sw)        -6827.7964   4575.744     -1.492      0.148   -1.62e+04    2577.780
CarName_toyota corolla liftback         -1.166e+04   4730.119     -2.465      0.021   -2.14e+04   -1935.286
CarName_toyota corolla tercel           -1.704e+04   5072.195     -3.360      0.002   -2.75e+04   -6614.058
CarName_toyota corona                   -1.189e+04   4562.672     -2.605      0.015   -2.13e+04   -2507.387
CarName_toyota corona hardtop           -8382.8122   4862.340     -1.724      0.097   -1.84e+04    1611.870
CarName_toyota corona liftback          -1.271e+04   4675.314     -2.718      0.012   -2.23e+04   -3095.339
CarName_toyota corona mark ii           -1.238e+04   4412.183     -2.806      0.009   -2.15e+04   -3312.207
CarName_toyota cressida                 -1.029e+04   5436.045     -1.893      0.069   -2.15e+04     881.571
CarName_toyota mark ii                  -1.137e+04   4620.714     -2.461      0.021   -2.09e+04   -1873.577
CarName_toyota starlet                  -1.168e+04   4472.314     -2.611      0.015   -2.09e+04   -2484.906
CarName_toyota tercel                   -1.192e+04   4971.404     -2.398      0.024   -2.21e+04   -1703.723
CarName_toyouta tercel                  -9056.6737   5022.304     -1.803      0.083   -1.94e+04    1266.820
CarName_vokswagen rabbit                -1.473e+04   6434.181     -2.290      0.030    -2.8e+04   -1507.478

In [1]:
import numpy as np
from scipy.stats import chi2_contingency
tab_data = [[21, 16], [75, 60], [5, 10]]
res = chi2_contingency(tab_data)

In [2]:
res

Chi2ContingencyResult(statistic=np.float64(2.8239706434502656), pvalue=np.float64(0.24365906101675808), dof=2, expected_freq=array([[19.98395722, 17.01604278],
       [72.9144385 , 62.0855615 ],
       [ 8.10160428,  6.89839572]]))